# Generated by Django 4.0.7 on 2023-11-15 09:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SKU', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Shipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tracking_number', models.CharField(db_index=True, max_length=20)),
                ('carrier', models.CharField(choices=[('DHL', 'Dhl'), ('DPD', 'Dpd'), ('FedEx', 'Fedex'), ('GLS', 'Gls'), ('UPS', 'Ups')], db_index=True, max_length=20)),
                ('sender_address', models.CharField(max_length=200)),
                ('receiver_address', models.CharField(max_length=200)),
                ('receiver_city', models.CharField(max_length=45)),
                ('receiver_country', models.CharField(max_length=45)),
                ('receiver_zipcode', models.IntegerField()),
                ('status', models.CharField(choices=[('inbound-scan', 'Inbound Scan'), ('scanned', 'Scanned'), ('transit', 'Transit'), ('in-transit', 'In Transit'), ('delivery', 'Delivery')], default='inbound-scan', max_length=20)),
                ('weather', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='weather.weather')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShipmentArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='traceapi.articles')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity', to='traceapi.shipments')),
            ],
        ),
    ]
